/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0D0507",
        "surface": "#14090C",
        "surface-bright": "#1A0B10",
        "surface-variant": "#220E15",
        "surface-container": "#180A0E",
        "surface-container-low": "#12070A",
        "surface-container-lowest": "#0D0507",
        "surface-container-high": "#220E15",
        "surface-container-highest": "#2D121C",
        "surface-border": "#261016",
        "surface-secondary": "#1A0B10",
        "primary": "#F3ECE2",
        "on-primary": "#0D0507",
        "secondary": "#9E9387",
        "on-secondary": "#F3ECE2",
        "outline": "#38161E",
        "outline-variant": "#261016",
        "body-text": "#C4B9AC",
        "on-background": "#F3ECE2",
        "surface-tint": "#8B2635",
        "surface-dim": "#090305",
        "accent": "#8B2635",
        "accent-blue-soft": "#1A0B10",
        "burgundy": "#8B2635",
        "burgundy-dark": "#5E1722",
        "burgundy-light": "#B3394B",
        "bone": "#F3ECE2",
        "bone-muted": "#E8E1D4",
        "bone-taupe": "#9E9387",
        "wine-black": "#0D0507",
        "wine-surface": "#14090C",
        "wine-border": "#2A1016",
        "error": "#BA1A1A",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        "ambient": "0 8px 30px rgba(0,0,0,0.04)"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "margin-x": "32px",
        "gutter": "32px",
        "section-gap": "160px",
        "section-padding": "120px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "h1-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "hero-lg": ["Plus Jakarta Sans", "sans-serif"],
        "subheading": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
        "display": ["'Instrument Serif'", "Georgia", "serif"],
        "serif": ["'Instrument Serif'", "Georgia", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "h1": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "h2": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-mobile": ["56px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-lg": ["110px", { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "subheading": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
