/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#F5F1EA",
        "surface": "#EDE6DC",
        "surface-bright": "#FAF7F2",
        "surface-variant": "#E4DDD1",
        "surface-container": "#EDE6DC",
        "surface-container-low": "#F5F1EA",
        "surface-container-lowest": "#FAF7F2",
        "surface-container-high": "#E2DACB",
        "surface-container-highest": "#D7CEBF",
        "surface-border": "#DFD7CA",
        "surface-secondary": "#FAF7F2",
        "primary": "#631B27",
        "on-primary": "#F5F1EA",
        "secondary": "#6A6258",
        "on-secondary": "#141414",
        "outline": "#DFD7CA",
        "outline-variant": "#ECE5D9",
        "body-text": "#4A433B",
        "on-background": "#141414",
        "surface-tint": "#631B27",
        "surface-dim": "#EDE6DC",
        "accent": "#631B27",
        "accent-hover": "#782231",
        "accent-blue-soft": "#F0E9DF",
        "burgundy": "#631B27",
        "burgundy-dark": "#430E18",
        "burgundy-light": "#7E2535",
        "burgundy-subtle": "rgba(99, 27, 39, 0.08)",
        "bone": "#F5F1EA",
        "bone-light": "#FAF7F2",
        "bone-muted": "#EDE6DC",
        "bone-taupe": "#8C8276",
        "carbon": "#141414",
        "carbon-soft": "#22201E",
        "error": "#BA1A1A",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        "ambient": "0 8px 30px rgba(0,0,0,0.04)"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "margin-x": "32px",
        "gutter": "32px",
        "section-gap": "160px",
        "section-padding": "120px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "h1-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "hero-lg": ["Plus Jakarta Sans", "sans-serif"],
        "subheading": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
        "display": ["'Instrument Serif'", "Georgia", "serif"],
        "serif": ["'Instrument Serif'", "Georgia", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "h1": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "h2": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-mobile": ["56px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-lg": ["110px", { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "subheading": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
